# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Creation Date : 05-03-2016
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

.PHONY: all
all: hw1-sol

hw1-sol: hw1-sol.tex
	xelatex -shell-escape hw1-sol.tex
